arch_root: /mnt

# These are aliases that define file names with group vars for specific machine.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `group_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  Gazelle Professional: gazelle.yml
  XPS 13 9350: xps.yml

country: United States
locales:
  - en_US

user:
  name: jburwell
  comment: John Burwell
  group: jburwell
  groups:
    - sys
    - video
    - wheel
  shell: /bin/zsh
  email: meaux@cockamamy.net
