---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes

  pre_tasks:
    - include_vars: "group_vars/{{ machine_aliases[ansible_product_name] }}"

    - name: update repository mirrors
      command: reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist

  roles:
    - pacman
    - arch-base
    - xorg
    - ssh
    - network
    - lxdm
    - xmonad
    - web
    - laptop
    - desktop
